name: .NET

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Publish
      run: dotnet publish -o ./dist
      
    - name: Copy files to AWS EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: ".,!node_modules"
        target: "~/api/api-topic-manager"

    # Instalar as dependencias no servidor e reiniciar
    - name: Install depencies on AWS EC2 and restart service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd api/api-topic-manager
          docker build -t topic-manager .
          docker stop topic-manager
          docker rm topic-manager
          docker container run -p 5005:5005 --name topic-manager -d topic-manager
